services:
    db:
        image: 'postgres:14-alpine'
        container_name: db
        environment:
            - POSTGRES_USER=example
            - POSTGRES_PASSWORD=example
            - POSTGRES_DB=example
        ports:
            - "5432:5432"
