name: Deployment

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: 'gradle'
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
            -   name: Build
                run: ./gradlew build --no-daemon
            -   run: npm install -g aws-cdk
            -   name: Build infrastructure
                run: cdk deploy
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_DEFAULT_REGION: 'eu-west-1'

